# Generated by Django 3.2.7 on 2021-09-06 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.BigIntegerField()),
                ('senha', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioUnico',
            fields=[
                ('usuario_unico_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uniqueUser.usuario')),
            ],
            options={
                'db_table': 'usuario_unico',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('serial_number_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uniqueUser.usuario')),
            ],
            options={
                'db_table': 'serial_number',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('ip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.BigIntegerField(blank=True, null=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uniqueUser.usuario')),
            ],
            options={
                'db_table': 'ip',
            },
        ),
    ]
