# Generated by Django 3.2.7 on 2021-10-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.BigIntegerField()),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    
        migrations.CreateModel(
            name='DadosEntropicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cookies_enabled', models.BooleanField()),
                ('device_memory', models.BigIntegerField()),
                ('hardware_concurrency', models.BigIntegerField()),
                ('languages', models.CharField(max_length=20)),
                ('local_storage', models.BooleanField()),
                ('platform', models.CharField(max_length=20)),
                ('session_storage', models.BooleanField()),
                ('timezone', models.CharField(max_length=50)),
                ('touch_support', models.BooleanField()),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_flavors', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dados_entropicos_user',
            },
        ),

    ]
